import { createClient } from '@supabase/supabase-js';
import './class-dolls.css';
import './class-tasks-dialog.css';
import vosImage from './class-dolls/vos.png';
import pompomImage from './class-dolls/pompom.png';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const app=()=>document.querySelector('#app');
let pageActive=false;
let profile=null;
let students=[];
let current=[];
let history=[];
let rolling=false;
let statusMessage='';
let statusError=false;

function mondayKey(){const d=new Date();const day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(12,0,0,0);return d.toISOString().slice(0,10)}
function shuffle(values){return values.map(value=>({value,order:Math.random()})).sort((a,b)=>a.order-b.order).map(x=>x.value)}
function studentName(id){return students.find(s=>s.id===id)?.name||'Nog te kiezen'}
function weekLabel(key){const start=new Date(`${key}T12:00:00`);const end=new Date(start);end.setDate(start.getDate()+6);const fmt=new Intl.DateTimeFormat('nl-BE',{day:'numeric',month:'short'});return `${fmt.format(start)} – ${fmt.format(end)}`}
async function getProfile(){const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data}=await supabase.from('profiles').select('id,display_name,role,active').eq('id',user.id).maybeSingle();return data?.active?data:null}
async function loadData(){const week=mondayKey();const [studentResult,currentResult,historyResult]=await Promise.all([supabase.from('class_students').select('id,name,active').eq('active',true).order('name'),supabase.from('class_puppet_assignments').select('id,week_start,puppet_slot,student_id,puppet_cycle,created_at').eq('week_start',week).order('puppet_slot'),supabase.from('class_puppet_assignments').select('id,week_start,puppet_slot,student_id,puppet_cycle,created_at').order('week_start',{ascending:false}).order('puppet_slot')]);students=studentResult.data||[];current=currentResult.data||[];history=historyResult.data||[]}
function go(page){pageActive=false;const eventName=page==='tasks'?'k3paalbos:tasks':'k3paalbos:navigate';window.dispatchEvent(new CustomEvent(eventName,{detail:{page}}))}
function header(){const name=profile?.display_name||'Welkom';return `<header class="topbar"><div class="brand"><div class="fox">🦊</div><div><h1>De Vosjes</h1><p>Klaspoppen op avontuur</p></div></div><nav class="main-nav"><button class="nav-item" data-dolls-go="calendar"><span>📅</span><small>Maandkalender</small></button><button class="nav-item" data-dolls-go="week"><span>🗓️</span><small>Weekkalender</small></button><button class="nav-item" data-dolls-go="day"><span>➡️</span><small>Dagverloop</small></button><button class="nav-item" data-dolls-go="weather"><span>🌤️</span><small>Weer</small></button><button class="nav-item" data-dolls-go="clothing"><span>👕</span><small>Kleding</small></button><button class="nav-item" data-dolls-go="tasks"><span>🎲</span><small>Klastaken</small></button><button class="nav-item active"><span>🧸</span><small>Klaspoppen</small></button></nav><div class="account">${name} <button id="dolls-logout">Uitloggen</button></div></header>`}
function currentFor(slot){return current.find(row=>row.puppet_slot===slot)}
function historyRows(){const weeks=[...new Set(history.map(row=>row.week_start))].slice(0,8);if(!weeks.length)return '<p class="dolls-empty-history">Nog geen historiek. Deze week wordt de eerste echte verdeling.</p>';return weeks.map(week=>{const rows=history.filter(row=>row.week_start===week);const vos=rows.find(row=>row.puppet_slot===1);const pompom=rows.find(row=>row.puppet_slot===2);return `<div class="dolls-history-row"><span class="dolls-history-week">${weekLabel(week)}</span><span><strong>Vos:</strong> ${vos?studentName(vos.student_id):'—'}</span><span><strong>Pompom:</strong> ${pompom?studentName(pompom.student_id):'—'}</span></div>`}).join('')}
function render(){if(!pageActive)return;const canEdit=profile?.role==='teacher';const vos=currentFor(1),pompom=currentFor(2);const historyAdmin=canEdit?`<div class="dolls-history-admin"><div><strong>Historiek wissen</strong><p>Alle klaspopverdelingen worden verwijderd. De leerlingenlijst blijft behouden.</p></div><div class="dolls-history-reset-row"><input id="dolls-history-password" type="password" placeholder="Beheerwachtwoord" autocomplete="current-password"><button id="reset-dolls-history" class="dolls-danger-button">Historiek resetten</button></div></div>`:'';app().innerHTML=`<main class="page dolls-page">${header()}<section class="dolls-shell"><div class="dolls-heading"><h2>Wie mag onze klaspoppen meenemen?</h2></div><div class="dolls-stage"><article class="doll-card doll-card-fox"><div class="doll-image-wrap"><img src="${vosImage}" alt="Klaspop Vos"></div><div class="doll-student ${vos?'chosen':''}">${vos?studentName(vos.student_id):'Nog te kiezen'}</div></article><div class="dolls-dice-column"><button class="dolls-dice" id="roll-dolls" ${!canEdit||students.length<2||rolling?'disabled':''} aria-label="Dobbel voor de klaspoppen"><span class="dolls-dice-image" role="img" aria-label="Dobbelsteen">🎲</span></button></div><article class="doll-card doll-card-pompom"><div class="doll-image-wrap"><img src="${pompomImage}" alt="Klaspop Pompom"></div><div class="doll-student ${pompom?'chosen':''}">${pompom?studentName(pompom.student_id):'Nog te kiezen'}</div></article></div>${students.length<2?'<div class="dolls-warning">Voeg minstens twee actieve kleuters toe bij Klastaken.</div>':''}${statusMessage?`<div class="dolls-status ${statusError?'error':''}">${statusMessage}</div>`:''}<details class="dolls-history"><summary>📚 Historiek bekijken</summary><div class="dolls-history-list">${historyRows()}</div>${historyAdmin}</details></section></main>`;bind(canEdit)}
function bind(canEdit){document.querySelector('#dolls-logout').onclick=()=>supabase.auth.signOut();document.querySelectorAll('[data-dolls-go]').forEach(button=>button.onclick=()=>go(button.dataset.dollsGo));if(canEdit){document.querySelector('#roll-dolls')?.addEventListener('click',rollDolls);document.querySelector('#reset-dolls-history')?.addEventListener('click',resetHistory)}}
function slotChoice(slot,historyWithoutCurrent,excludeId=null){const slotHistory=historyWithoutCurrent.filter(row=>row.puppet_slot===slot);const maxCycle=Math.max(1,...slotHistory.map(row=>row.puppet_cycle||1));let cycle=maxCycle;const used=new Set(slotHistory.filter(row=>(row.puppet_cycle||1)===cycle).map(row=>row.student_id));let available=students.filter(student=>!used.has(student.id)&&student.id!==excludeId);if(!available.length){cycle=maxCycle+1;available=students.filter(student=>student.id!==excludeId)}return {student:shuffle(available)[0]||null,cycle}}
function showDiceAnimation(){document.querySelector('.tasks-dice-overlay')?.remove();const overlay=document.createElement('div');overlay.className='tasks-dice-overlay';overlay.setAttribute('role','status');overlay.setAttribute('aria-live','polite');overlay.innerHTML='<div class="tasks-dice-stage"><div class="tasks-dice-title">Dobbelen…</div><div class="tasks-dice-stars">✨ ⭐ ✨</div><div class="tasks-dice-big">🎲</div><div class="tasks-dice-subtitle">Wie mogen de klaspoppen meenemen?</div></div>';document.body.appendChild(overlay);void overlay.offsetHeight;return overlay}
async function rollDolls(){if(rolling||students.length<2)return;const week=mondayKey();if(current.length){const again=window.confirm('Er is al een klaspoppenverdeling voor deze week. Wil je opnieuw dobbelen? De huidige namen worden vervangen.');if(!again)return}rolling=true;statusMessage='';statusError=false;render();const overlay=showDiceAnimation();await new Promise(resolve=>setTimeout(resolve,2600));overlay.remove();const historyWithoutCurrent=history.filter(row=>row.week_start!==week);const first=slotChoice(1,historyWithoutCurrent);const second=slotChoice(2,historyWithoutCurrent,first.student?.id||null);if(!first.student||!second.student){rolling=false;statusMessage='Er zijn niet genoeg actieve kleuters om twee verschillende namen te kiezen.';statusError=true;render();return}if(current.length){const {error:deleteError}=await supabase.from('class_puppet_assignments').delete().eq('week_start',week);if(deleteError){rolling=false;statusMessage=`Opnieuw dobbelen lukt niet: ${deleteError.message}`;statusError=true;render();return}}const rows=[{week_start:week,puppet_slot:1,student_id:first.student.id,puppet_cycle:first.cycle,created_by:profile?.id||null},{week_start:week,puppet_slot:2,student_id:second.student.id,puppet_cycle:second.cycle,created_by:profile?.id||null}];const {error}=await supabase.from('class_puppet_assignments').insert(rows);if(error){rolling=false;statusMessage=`Opslaan mislukt: ${error.message}`;statusError=true;await loadData();render();return}await loadData();rolling=false;statusMessage='🎉 De klaspoppen hebben hun logeeradres voor deze week gekozen!';render()}
function confirmHistoryReset(){return new Promise(resolve=>{const previousFocus=document.activeElement;const overlay=document.createElement('div');overlay.className='tasks-dialog-overlay';overlay.innerHTML=`<section class="tasks-dialog" role="dialog" aria-modal="true" aria-labelledby="dolls-reset-title" aria-describedby="dolls-reset-description"><div class="tasks-dialog-icon" aria-hidden="true">🗑️</div><h2 id="dolls-reset-title">Historiek verwijderen?</h2><p id="dolls-reset-description">Ben je zeker dat je de volledige historiek van de klaspoppen wilt wissen? Ook de verdeling van deze week wordt verwijderd. De leerlingenlijst blijft behouden.</p><div class="tasks-dialog-actions"><button type="button" class="tasks-dialog-cancel">Historiek behouden</button><button type="button" class="tasks-dialog-confirm"><span aria-hidden="true">🗑️</span> Historiek verwijderen</button></div></section>`;document.body.appendChild(overlay);document.body.classList.add('tasks-dialog-open');const cancel=overlay.querySelector('.tasks-dialog-cancel');const confirm=overlay.querySelector('.tasks-dialog-confirm');const buttons=[cancel,confirm];const close=result=>{document.removeEventListener('keydown',onKeydown);overlay.remove();document.body.classList.remove('tasks-dialog-open');previousFocus?.focus?.();resolve(result)};const onKeydown=event=>{if(event.key==='Escape'){event.preventDefault();close(false);return}if(event.key==='Tab'){const currentIndex=buttons.indexOf(document.activeElement);if(event.shiftKey&&currentIndex<=0){event.preventDefault();confirm.focus()}else if(!event.shiftKey&&currentIndex===buttons.length-1){event.preventDefault();cancel.focus()}}};cancel.onclick=()=>close(false);confirm.onclick=()=>close(true);overlay.onclick=event=>{if(event.target===overlay)close(false)};document.addEventListener('keydown',onKeydown);cancel.focus()})}
async function resetHistory(){const password=document.querySelector('#dolls-history-password')?.value||'';if(!password){statusMessage='Vul het beheerwachtwoord in om de historiek te wissen.';statusError=true;render();return}const confirmed=await confirmHistoryReset();if(!confirmed)return;const {error}=await supabase.rpc('class_puppets_reset',{p_password:password});if(error){statusMessage=error.message;statusError=true;render();return}await loadData();statusMessage='✅ De klaspoppenhistoriek is gewist.';statusError=false;render()}
async function openDolls(){pageActive=true;profile=await getProfile();if(!profile)return;await loadData();render()}
window.addEventListener('k3paalbos:dolls',()=>openDolls());
