import { createClient } from '@supabase/supabase-js';
import './style.css';
import { showWeather } from './weather.js';
import { showClothing } from './clothing.js';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const calendarIcons=[['🌳','Buiten'],['🏅','Sportdag'],['🏊','Zwemmen'],['🗣️','Gespreksmoment'],['🚦','Verkeer'],['🎭','Toneel'],['🎬','Film'],['🗄️','Bib'],['🚌','Bus'],['🚶','Op stap'],['⭐','Speciale act.'],['🌷','Moederdag'],['💙','Vaderdag'],['🎉','Feest'],['🎄','Kerstdag'],['🐣','Pasen'],['👑','Sinterklaas'],['🎂','Verjaardag']].map(([icon,label])=>({icon,label}));
const weekActivityGroups=[
  {name:'Bewegen & ontspannen',items:[['🌳','Buiten'],['🏃','Bewegen'],['🤸','Turnen'],['🏊','Zwemmen'],['🧘','Yoga'],['🏅','Sportdag']]},
  {name:'Samen & zorg',items:[['🤲','Hartje'],['❤️','Zorg'],['👥','Kleine groep'],['💬','Babbelronde'],['🗣️','Gespreksmoment']]},
  {name:'Leren',items:[['🔢','Wiskunde'],['🗣️','Taal'],['🔠','Letters'],['✏️','Schrijven'],['🔬','STEM'],['🚦','Verkeer'],['🇫🇷','Frans']]},
  {name:'Lezen, spelen & creatief',items:[['📚','Lezen'],['🎨','Knutselen'],['🎵','Muziek'],['🎲','Opvoedende spelen'],['🧩','Puzzelen'],['🎭','Toneel'],['🎬','Film'],['📖','Voorlezen'],['🗄️','Bib']]},
  {name:'Op stap & bijzonder',items:[['🚌','Bus'],['🚶','Op stap'],['⭐','Speciale act.']]},
  {name:'Feestdagen',items:[['🌷','Moederdag'],['💙','Vaderdag'],['🎉','Feest'],['🎄','Kerst'],['🐣','Pasen'],['👑','Sinterklaas']]}
];
const weekActivities=weekActivityGroups.flatMap(g=>g.items).map(([icon,label])=>({icon,label}));
const weekDays=[{id:1,name:'Maandag',color:'green'},{id:2,name:'Dinsdag',color:'green'},{id:3,name:'Woensdag',color:'wednesday'},{id:4,name:'Donderdag',color:'green'},{id:5,name:'Vrijdag',color:'green'},{id:6,name:'Zaterdag',color:'blue'},{id:7,name:'Zondag',color:'blue'}];
const months=['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december'],weekdays=['ma','di','wo','do','vr','za','zo'];
const now=new Date();let viewDate=new Date(now.getFullYear(),now.getMonth(),1),items=[],profile=null,dragged=null,currentPage='calendar';
const app=document.querySelector('#app'),storageKey='k3paalbos-weekcalendar-v2';
const pad=n=>String(n).padStart(2,'0'),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,firstMonday=d=>d.getDay()===0?6:d.getDay()-1,daysIn=d=>new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),today=d=>key(d)===key(now);
function login(message=''){app.innerHTML=`<main class="login-page"><section class="login-card"><div class="login-fox">🦊</div><h1>De Vosjes</h1><p>Welkom! Log in om de kalender te bekijken.</p><form id="login"><label>E-mailadres<input id="email" type="email" autocomplete="username" required placeholder="juf@school.be"></label><label>Wachtwoord<input id="password" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">🦊 Inloggen</button><div class="error">${message}</div></form></section></main>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;b.textContent='Even wachten…';const {error}=await supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)return login('E-mailadres of wachtwoord klopt niet.');await start()}}
async function getProfile(id){const {data,error}=await supabase.from('profiles').select('id,display_name,role,active').eq('id',id).single();return error||!data||!data.active?null:data}
function denied(){app.innerHTML=`<main class="login-page"><section class="login-card"><div class="login-fox">🦊</div><h1>Geen toegang</h1><p>Dit account heeft geen toegang tot De Vosjes.</p><button class="primary" id="out">Uitloggen</button></section></main>`;document.querySelector('#out').onclick=()=>supabase.auth.signOut()}
async function load(){const {data,error}=await supabase.from('calendar_items').select('*').order('position');if(!error)items=data||[]}
function header(active){return `<header class="topbar"><div class="brand"><div class="fox">🦊</div><div><h1>De Vosjes</h1><p>${profile.role==='teacher'?'Beheer de activiteiten':'Bekijk de activiteiten'}</p></div></div><nav class="main-nav"><button class="nav-item ${active==='calendar'?'active':''}" data-page="calendar"><span>📅</span><small>Kalender</small></button><button class="nav-item ${active==='week'?'active':''}" data-page="week"><span>🗓️</span><small>Weekkalender</small></button><button class="nav-item ${active==='weather'?'active':''}" data-page="weather"><span>🌤️</span><small>Weer</small></button><button class="nav-item ${active==='clothing'?'active':''}" data-page="clothing"><span>👕</span><small>Kleding</small></button></nav><div class="account">${profile.display_name||'Welkom'} <button id="logout">Uitloggen</button></div></header>`}
function navigate(page){currentPage=page;renderPage()}
function bindHeader(){document.querySelector('#logout').onclick=()=>supabase.auth.signOut();document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
function renderCalendar(){const y=viewDate.getFullYear(),m=viewDate.getMonth(),canEdit=profile.role==='teacher';let cells='';for(let i=0;i<firstMonday(viewDate);i++)cells+='<div class="day empty"></div>';for(let d=1;d<=daysIn(viewDate);d++){const date=new Date(y,m,d),k=key(date),di=items.filter(x=>x.day===k).sort((a,b)=>a.position-b.position);cells+=`<div class="day ${today(date)?'today':''}" data-day="${k}"><div class="day-number">${d}</div><div class="day-items">${di.map(x=>`<div class="placed"><span>${x.icon}</span><small>${x.label}</small>${canEdit?`<button class="remove" data-id="${x.id}">×</button>`:''}</div>`).join('')}</div></div>`}app.innerHTML=`<main class="page">${header('calendar')}<section class="content">${canEdit?`<aside class="panel"><h2>Activiteiten</h2><p>Sleep of tik op een pictogram en kies daarna een dag.</p><div class="icons">${calendarIcons.map((x,i)=>`<button class="icon" draggable="true" data-i="${i}"><span>${x.icon}</span><small>${x.label}</small></button>`).join('')}</div><button class="todaybtn" id="todaybtn">📅 Naar vandaag</button></aside>`:`<aside class="panel readonly"><div class="bigfox">🦊</div><h2>Welkom!</h2><p>Je kunt de kalender bekijken. Alleen de juf kan activiteiten aanpassen.</p></aside>`}<section class="calendar-wrap"><div class="calendar-head"><button class="nav" id="prev">‹</button><h2>${months[m]} ${y}</h2><button class="nav" id="next">›</button></div><div class="weekdays">${weekdays.map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar">${cells}</div></section></section><footer>🦊 Een fijne dag begint met weten wat er komt.</footer></main>`;bindHeader();document.querySelector('#prev').onclick=()=>{viewDate=new Date(y,m-1,1);renderPage()};document.querySelector('#next').onclick=()=>{viewDate=new Date(y,m+1,1);renderPage()};document.querySelector('#todaybtn')?.addEventListener('click',()=>{viewDate=new Date(now.getFullYear(),now.getMonth(),1);renderPage()});if(!canEdit)return;document.querySelectorAll('.icon').forEach(b=>{const set=()=>dragged={type:'calendar',value:calendarIcons[+b.dataset.i]};b.ondragstart=set;b.addEventListener('pointerdown',set);b.addEventListener('pointerup',e=>{const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.day:not(.empty)');if(el&&dragged?.type==='calendar')add(el.dataset.day,dragged.value)})});document.querySelectorAll('.day:not(.empty)').forEach(day=>{day.ondragover=e=>{e.preventDefault();day.classList.add('over')};day.ondragleave=()=>day.classList.remove('over');day.ondrop=e=>{e.preventDefault();day.classList.remove('over');if(dragged?.type==='calendar')add(day.dataset.day,dragged.value);dragged=null};day.onclick=()=>{if(dragged?.type==='calendar'){add(day.dataset.day,dragged.value);dragged=null}}});document.querySelectorAll('.remove').forEach(b=>b.onclick=async e=>{e.stopPropagation();const {error}=await supabase.from('calendar_items').delete().eq('id',b.dataset.id);if(!error){items=items.filter(x=>x.id!==b.dataset.id);renderPage()}})}
function emptyWeek(){return {days:{},activities:{}}}function loadWeek(){try{return {...emptyWeek(),...(JSON.parse(localStorage.getItem(storageKey))||{})}}catch{return emptyWeek()}}function saveWeek(s){localStorage.setItem(storageKey,JSON.stringify(s))}
function renderWeek(){const canEdit=profile.role==='teacher',state=loadWeek();const columns=weekDays.map(slot=>{const placed=state.days[slot.id],display=placed||slot,acts=state.activities[slot.id]||[];const maxActivities=display.id===3?4:5;return `<div class="week-column ${display.color}" data-slot="${slot.id}"><div class="week-day-head">${placed?`<div class="placed-day" draggable="true" data-day-id="${placed.id}"><span>${placed.id}</span><strong>${placed.name}</strong></div>`:'<div class="empty-day-drop">Sleep dag hier</div>'}</div><div class="activity-zone ${display.id===3?'wednesday-zone':''}" data-activity-day="${slot.id}">${acts.map((a,i)=>`<div class="week-activity" draggable="true" data-act-day="${slot.id}" data-act-index="${i}"><span>${a.icon}</span><small>${a.label}</small><button type="button" class="remove-week" draggable="false" data-day="${slot.id}" data-index="${i}">×</button></div>`).join('')}${acts.length<maxActivities?'<div class="activity-hint">+ Sleep activiteit hier</div>':''}</div>${display.id===3?'<div class="wednesday-afternoon"><span>🌙</span><small>Geen school in de namiddag</small></div>':''}</div>`}).join('');const dayPalette=weekDays.map(d=>`<button class="day-token ${d.color}" draggable="true" data-day-id="${d.id}"><span>${d.id}</span>${d.name}</button>`).join('');const activityPalette=weekActivityGroups.map((group,gi)=>`<details class="activity-group" ${gi===0?'open':''}><summary>${group.name}</summary><div class="activity-palette">${group.items.map((x,i)=>{const index=weekActivities.findIndex(a=>a.icon===x[0]&&a.label===x[1]);return `<button class="activity-token" draggable="true" data-act-id="${index}"><span>${x[0]}</span><small>${x[1]}</small></button>`}).join('')}</div></details>`).join('');app.innerHTML=`<main class="page">${header('week')}<section class="week-content"><section class="week-wrap"><div class="week-title"><div><h2>Weekkalender</h2><p>Sleep de dagen en daarna de activiteiten naar de juiste plek.</p></div>${canEdit?'<button class="clear-week" id="clear-week">🗑️ Wissen</button>':''}</div><div class="week-grid">${columns}</div><div class="day-palette-bottom"><h3>Dagen van de week</h3><p>Sleep de dagen naar het rooster.</p><div class="day-palette">${dayPalette}</div></div></section><aside class="week-sidebar"><div class="palette-section"><h2>Activiteiten</h2><p>Open een rubriek en sleep een pictogram naar een dag.</p><div class="activity-groups">${activityPalette}</div></div><div class="tip">💡 <span>Sleep eerst de dagen naar het rooster. Daarna de activiteiten in hetzelfde vak.</span></div></aside></section></main>`;bindHeader();if(!canEdit)return;
 document.querySelectorAll('.day-token').forEach(b=>{const set=()=>dragged={type:'day',value:weekDays.find(d=>d.id===+b.dataset.dayId)};b.ondragstart=set;b.addEventListener('pointerdown',set);b.addEventListener('pointerup',e=>dropDay(e))});
 document.querySelectorAll('.placed-day').forEach(b=>{const set=()=>dragged={type:'day',value:weekDays.find(d=>d.id===+b.dataset.dayId)};b.ondragstart=set;b.addEventListener('pointerdown',set);b.addEventListener('pointerup',e=>dropDay(e))});
 document.querySelectorAll('.activity-token').forEach(b=>{const set=()=>dragged={type:'activity',value:weekActivities[+b.dataset.actId]};b.ondragstart=set;b.addEventListener('pointerdown',set);b.addEventListener('pointerup',e=>dropActivity(e))});
 document.querySelectorAll('.week-activity').forEach(el=>{const set=e=>{if(e.target.closest('.remove-week'))return;const s=loadWeek(),a=(s.activities[el.dataset.actDay]||[])[+el.dataset.actIndex];if(a)dragged={type:'move-activity',value:{...a,from:+el.dataset.actDay,index:+el.dataset.actIndex}}};el.ondragstart=set;el.addEventListener('pointerdown',set);el.addEventListener('pointerup',e=>{if(e.target.closest('.remove-week'))return;dropActivity(e)});});
 document.querySelectorAll('.week-column').forEach(c=>{c.ondragover=e=>{if(dragged?.type==='day'){e.preventDefault();c.classList.add('over')}};c.ondragleave=()=>c.classList.remove('over');c.ondrop=e=>{e.preventDefault();c.classList.remove('over');if(dragged?.type==='day')placeDay(+c.dataset.slot,dragged.value);dragged=null}});
 document.querySelectorAll('.activity-zone').forEach(z=>{z.ondragover=e=>{if(dragged?.type!=='day'){e.preventDefault();z.classList.add('over')}};z.ondragleave=()=>z.classList.remove('over');z.ondrop=e=>{e.preventDefault();z.classList.remove('over');dropActivity(e)}});
 document.querySelectorAll('.remove-week').forEach(b=>{b.onpointerdown=e=>{e.stopPropagation()};b.onpointerup=e=>{e.stopPropagation()};b.onclick=e=>{e.preventDefault();e.stopPropagation();const s=loadWeek();const day=b.dataset.day,index=+b.dataset.index;s.activities[day]=(s.activities[day]||[]).filter((_,i)=>i!==index);saveWeek(s);dragged=null;renderPage()}});
 document.querySelector('#clear-week')?.addEventListener('click',()=>{saveWeek(emptyWeek());renderPage()})}
function dropDay(e){const c=document.elementFromPoint(e.clientX,e.clientY)?.closest('.week-column');if(c&&dragged?.type==='day')placeDay(+c.dataset.slot,dragged.value);dragged=null}
function placeDay(slot,day){const s=loadWeek();Object.keys(s.days).forEach(k=>{if(s.days[k]?.id===day.id)delete s.days[k]});s.days[slot]=day;saveWeek(s);renderPage()}
function dropActivity(e){const z=document.elementFromPoint(e.clientX,e.clientY)?.closest('.activity-zone');if(!z||!dragged)return;const day=+z.dataset.activityDay;if(dragged.type==='activity')addWeekActivity(day,dragged.value);else if(dragged.type==='move-activity'){const s=loadWeek(),max=day===3?4:5;if(day!==dragged.value.from&&(s.activities[day]||[]).length>=max){dragged=null;return}s.activities[dragged.value.from]=(s.activities[dragged.value.from]||[]).filter((_,i)=>i!==dragged.value.index);(s.activities[day]||(s.activities[day]=[])).push({icon:dragged.value.icon,label:dragged.value.label});saveWeek(s);dragged=null;renderPage()}}
function addWeekActivity(day,a){const s=loadWeek(),max=day===3?4:5;if((s.activities[day]||[]).length>=max)return;(s.activities[day]||(s.activities[day]=[])).push(a);saveWeek(s);dragged=null;renderPage()}
async function add(day,icon){const position=items.filter(x=>x.day===day).length;const {data,error}=await supabase.from('calendar_items').insert({day,icon:icon.icon,label:icon.label,position}).select().single();if(!error){items.push(data);renderPage()}}
function renderPage(){if(currentPage==='week')return renderWeek();if(currentPage==='weather')return showWeather(navigate);if(currentPage==='clothing')return showClothing(navigate,profile);return renderCalendar()}
async function start(){const {data:{user}}=await supabase.auth.getUser();if(!user)return login();profile=await getProfile(user.id);if(!profile)return denied();await load();renderPage()}
supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){profile=null;items=[];currentPage='calendar';login()}});start();