import { createClient } from '@supabase/supabase-js';
import './style.css';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
const calendarIcons = [['📖','Bib'],['🚌','Uitstap'],['🤸','Turnen'],['🏊','Zwemmen'],['⭐','Speciale act.'],['🎂','Verjaardag']].map(([icon,label])=>({icon,label}));
const weekActivities = [['☀️','Zon'],['🌧️','Regen'],['☁️','Wolk'],['🌈','Regenboog'],['🌳','Buiten'],['🍎','Fruit'],['📚','Lezen'],['🎨','Knutselen'],['🎵','Muziek'],['🏃','Bewegen'],['🍽️','Eten'],['🤸','Turnen']].map(([icon,label])=>({icon,label}));
const weekDays = [
  {id:1,name:'Maandag',color:'green'}, {id:2,name:'Dinsdag',color:'green'}, {id:3,name:'Woensdag',color:'wednesday'},
  {id:4,name:'Donderdag',color:'green'}, {id:5,name:'Vrijdag',color:'green'}, {id:6,name:'Zaterdag',color:'blue'}, {id:7,name:'Zondag',color:'blue'}
];
const months=['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december'];
const weekdays=['ma','di','wo','do','vr','za','zo'];
const now=new Date(); let viewDate=new Date(now.getFullYear(),now.getMonth(),1); let items=[]; let profile=null; let draggedIcon=null; let currentPage='calendar';
const app=document.querySelector('#app');
const pad=n=>String(n).padStart(2,'0');
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const firstMonday=d=>d.getDay()===0?6:d.getDay()-1;
const daysIn=d=>new Date(d.getFullYear(),d.getMonth()+1,0).getDate();
const today=d=>key(d)===key(now);
const storageKey='k3paalbos-weekcalendar-v1';

function login(message=''){
 app.innerHTML=`<main class="login-page"><section class="login-card"><div class="login-fox">🦊</div><h1>De Vosjes</h1><p>Welkom! Log in om de kalender te bekijken.</p><form id="login"><label>E-mailadres<input id="email" type="email" autocomplete="username" required placeholder="juf@school.be"></label><label>Wachtwoord<input id="password" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">🦊 Inloggen</button><div class="error">${message}</div></form></section></main>`;
 document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;b.textContent='Even wachten…';const {error}=await supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)return login('E-mailadres of wachtwoord klopt niet.');await start();};
}
async function getProfile(id){const {data,error}=await supabase.from('profiles').select('id,display_name,role,active').eq('id',id).single();return error||!data||!data.active?null:data;}
function denied(){app.innerHTML=`<main class="login-page"><section class="login-card"><div class="login-fox">🦊</div><h1>Geen toegang</h1><p>Dit account heeft geen toegang tot De Vosjes.</p><button class="primary" id="out">Uitloggen</button></section></main>`;document.querySelector('#out').onclick=()=>supabase.auth.signOut();}
async function load(){const {data,error}=await supabase.from('calendar_items').select('*').order('position');if(!error)items=data||[];}
function header(active){return `<header class="topbar"><div class="brand"><div class="fox">🦊</div><div><h1>De Vosjes</h1><p>${profile.role==='teacher'?'Beheer de activiteiten':'Bekijk de activiteiten'}</p></div></div><nav class="main-nav" aria-label="Hoofdnavigatie"><button class="nav-item ${active==='calendar'?'active':''}" data-page="calendar"><span>📅</span><small>Kalender</small></button><button class="nav-item ${active==='week'?'active':''}" data-page="week"><span>🗓️</span><small>Weekkalender</small></button><button class="nav-item" disabled><span>🌤️</span><small>Weer</small></button><button class="nav-item" disabled><span>👕</span><small>Kleding</small></button></nav><div class="account">${profile.display_name||'Welkom'} <button id="logout">Uitloggen</button></div></header>`;}
function bindHeader(){document.querySelector('#logout').onclick=()=>supabase.auth.signOut();document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;renderPage()});}
function renderCalendar(){
 const y=viewDate.getFullYear(),m=viewDate.getMonth(),canEdit=profile.role==='teacher';let cells='';for(let i=0;i<firstMonday(viewDate);i++)cells+='<div class="day empty"></div>';
 for(let d=1;d<=daysIn(viewDate);d++){const date=new Date(y,m,d),k=key(date),di=items.filter(x=>x.day===k).sort((a,b)=>a.position-b.position);cells+=`<div class="day ${today(date)?'today':''}" data-day="${k}"><div class="day-number">${d}</div><div class="day-items">${di.map(x=>`<div class="placed"><span>${x.icon}</span><small>${x.label}</small>${canEdit?`<button class="remove" data-id="${x.id}">×</button>`:''}</div>`).join('')}</div></div>`;}
 app.innerHTML=`<main class="page">${header('calendar')}<section class="content">${canEdit?`<aside class="panel"><h2>Activiteiten</h2><p>Sleep of tik op een pictogram en kies daarna een dag.</p><div class="icons">${calendarIcons.map((x,i)=>`<button class="icon" draggable="true" data-i="${i}"><span>${x.icon}</span><small>${x.label}</small></button>`).join('')}</div><button class="todaybtn" id="todaybtn">📅 Naar vandaag</button></aside>`:`<aside class="panel readonly"><div class="bigfox">🦊</div><h2>Welkom!</h2><p>Je kunt de kalender bekijken. Alleen de juf kan activiteiten aanpassen.</p><button class="todaybtn" id="todaybtn">📅 Naar vandaag</button></aside>`}<section class="calendar-wrap"><div class="calendar-head"><button class="nav" id="prev">‹</button><h2>${months[m]} ${y}</h2><button class="nav" id="next">›</button></div><div class="weekdays">${weekdays.map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar">${cells}</div></section></section><footer>🦊 Een fijne dag begint met weten wat er komt.</footer></main>`;
 bindHeader();document.querySelector('#prev').onclick=()=>{viewDate=new Date(y,m-1,1);renderPage()};document.querySelector('#next').onclick=()=>{viewDate=new Date(y,m+1,1);renderPage()};document.querySelector('#todaybtn').onclick=()=>{viewDate=new Date(now.getFullYear(),now.getMonth(),1);renderPage()};
 if(!canEdit)return;
 document.querySelectorAll('.icon').forEach(b=>{b.ondragstart=()=>draggedIcon=calendarIcons[+b.dataset.i];b.onclick=()=>draggedIcon=calendarIcons[+b.dataset.i];b.addEventListener('pointerdown',()=>draggedIcon=calendarIcons[+b.dataset.i]);b.addEventListener('pointerup',e=>{const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.day:not(.empty)');if(el&&draggedIcon){const x=draggedIcon;draggedIcon=null;add(el.dataset.day,x)}})});
 document.querySelectorAll('.day:not(.empty)').forEach(day=>{day.ondragover=e=>{e.preventDefault();day.classList.add('over')};day.ondragleave=()=>day.classList.remove('over');day.ondrop=async e=>{e.preventDefault();day.classList.remove('over');if(draggedIcon)await add(day.dataset.day,draggedIcon)};day.onclick=async()=>{if(draggedIcon){const x=draggedIcon;draggedIcon=null;await add(day.dataset.day,x)}}});
 document.querySelectorAll('.remove').forEach(b=>b.onclick=async e=>{e.stopPropagation();const {error}=await supabase.from('calendar_items').delete().eq('id',b.dataset.id);if(!error){items=items.filter(x=>x.id!==b.dataset.id);renderPage()}});
}
function defaultWeek(){return {days:{},activities:{}};}
function loadWeek(){try{return {...defaultWeek(),...(JSON.parse(localStorage.getItem(storageKey))||{})}}catch{return defaultWeek()}}
function saveWeek(data){localStorage.setItem(storageKey,JSON.stringify(data))}
function renderWeek(){
 const canEdit=profile.role==='teacher',state=loadWeek();
 const columns=weekDays.map(day=>{const placedDay=state.days[day.id];const acts=state.activities[day.id]||[];return `<div class="week-column ${day.color}" data-slot="${day.id}"><div class="week-day-head"><span class="day-number-box">${day.id}</span><div><strong>${day.name}</strong>${day.id===3?'<small>(halve dag)</small>':''}</div></div><div class="activity-zone ${day.id===3?'wednesday-school':''}" data-activity-day="${day.id}">${placedDay?`<div class="placed-week-day" draggable="true" data-placed-day="${placedDay.id}"><span>${placedDay.id}</span>${placedDay.name}</div>`:'<div class="day-drop-hint">Sleep de dag hier</div>'}${acts.map((a,i)=>`<div class="week-activity" draggable="true" data-act-day="${day.id}" data-act-index="${i}"><span>${a.icon}</span><small>${a.label}</small><button class="remove-week" data-day="${day.id}" data-index="${i}" aria-label="Verwijder">×</button></div>`).join('')}</div>${day.id===3?'<div class="wednesday-afternoon"><span>🌙</span><small>Geen school in de namiddag</small></div>':''}</div>`}).join('');
 const dayPalette=weekDays.map(d=>`<button class="day-token ${d.color}" draggable="true" data-day-id="${d.id}"><span>${d.id}</span>${d.name}</button>`).join('');
 const activityPalette=weekActivities.map((x,i)=>`<button class="activity-token" draggable="true" data-act-id="${i}"><span>${x.icon}</span><small>${x.label}</small></button>`).join('');
 app.innerHTML=`<main class="page">${header('week')}<section class="week-content"><aside class="week-sidebar"><div class="palette-section"><h2>Dagen van de week</h2><p>Sleep de dagen naar het rooster.</p><div class="day-palette">${dayPalette}</div></div><div class="palette-section"><h2>Activiteiten</h2><p>Sleep de activiteiten naar een dag.</p><div class="activity-palette">${activityPalette}</div></div><div class="tip">💡 <span>Sleep eerst de dagen naar het rooster. Daarna kun je de activiteiten in hetzelfde vak plaatsen.</span></div></aside><section class="week-wrap"><div class="week-title"><div><h2>Weekkalender</h2><p>Sleep de dagen en daarna de activiteiten naar de juiste plek.</p></div>${canEdit?'<button class="clear-week" id="clear-week">🗑️ Wissen</button>':''}</div><div class="week-grid">${columns}</div><div class="week-note">⭐ Woensdag is een halve dag. Activiteiten kunnen alleen in het groene gedeelte geplaatst worden.</div></section></section></main>`;
 bindHeader();
 if(!canEdit)return;
 document.querySelectorAll('.day-token').forEach(b=>{b.ondragstart=()=>draggedIcon={type:'day',value:weekDays.find(d=>d.id===+b.dataset.dayId)};b.addEventListener('pointerdown',()=>draggedIcon={type:'day',value:weekDays.find(d=>d.id===+b.dataset.dayId)});b.addEventListener('pointerup',e=>dropWeek(e))});
 document.querySelectorAll('.activity-token').forEach(b=>{b.ondragstart=()=>draggedIcon={type:'activity',value:weekActivities[+b.dataset.actId]};b.addEventListener('pointerdown',()=>draggedIcon={type:'activity',value:weekActivities[+b.dataset.actId]});b.addEventListener('pointerup',e=>dropWeek(e))});
 document.querySelectorAll('.activity-zone').forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.classList.add('over')};zone.ondragleave=()=>zone.classList.remove('over');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('over');dropWeek(e)} });
 document.querySelectorAll('.placed-week-day').forEach(el=>{el.addEventListener('dragstart',()=>{draggedIcon={type:'day',value:weekDays.find(d=>d.id===+el.dataset.placedDay)} });el.addEventListener('pointerdown',()=>draggedIcon={type:'day',value:weekDays.find(d=>d.id===+el.dataset.placedDay)});el.addEventListener('pointerup',e=>dropWeek(e))});
 document.querySelectorAll('.week-activity').forEach(el=>{el.addEventListener('dragstart',()=>{draggedIcon={type:'move-activity',value:{...weekActivities.find(x=>x.label===el.querySelector('small').textContent),from:+el.dataset.actDay,index:+el.dataset.actIndex}}});el.addEventListener('pointerdown',()=>draggedIcon={type:'move-activity',value:{...weekActivities.find(x=>x.label===el.querySelector('small').textContent),from:+el.dataset.actDay,index:+el.dataset.actIndex}});el.addEventListener('pointerup',e=>dropWeek(e))});
 document.querySelectorAll('.remove-week').forEach(b=>b.onclick=e=>{e.stopPropagation();const s=loadWeek();s.activities[b.dataset.day]=(s.activities[b.dataset.day]||[]).filter((_,i)=>i!==+b.dataset.index);saveWeek(s);renderPage()});
 document.querySelector('#clear-week')?.addEventListener('click',()=>{saveWeek(defaultWeek());renderPage()});
}
function dropWeek(e){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.activity-zone');if(!target||!draggedIcon)return;const day=+target.dataset.activityDay;if(draggedIcon.type==='activity')addWeekActivity(day,draggedIcon.value);else if(draggedIcon.type==='move-activity'){const s=loadWeek();s.activities[draggedIcon.value.from]=(s.activities[draggedIcon.value.from]||[]).filter((_,i)=>i!==draggedIcon.value.index);if((s.activities[day]||[]).length<5)(s.activities[day]||(s.activities[day]=[])).push(draggedIcon.value);saveWeek(s);draggedIcon=null;renderPage()}else if(draggedIcon.type==='day'){const s=loadWeek();const oldDay=Object.values(s.days).find(d=>d.id===draggedIcon.value.id);if(oldDay){Object.keys(s.days).forEach(k=>{if(s.days[k]?.id===draggedIcon.value.id)delete s.days[k]})}s.days[day]=draggedIcon.value;saveWeek(s);draggedIcon=null;renderPage()}}
function addWeekActivity(day,activity){if(day===3 && loadWeek().activities[day]?.length>=5)return;const s=loadWeek();if((s.activities[day]||[]).length>=5)return;(s.activities[day]||(s.activities[day]=[])).push(activity);saveWeek(s);draggedIcon=null;renderPage()}
async function add(day,icon){const position=items.filter(x=>x.day===day).length;const {data,error}=await supabase.from('calendar_items').insert({day,icon:icon.icon,label:icon.label,position}).select().single();if(!error){items.push(data);draggedIcon=null;renderPage()}}
function renderPage(){currentPage==='week'?renderWeek():renderCalendar()}
async function start(){const {data:{user}}=await supabase.auth.getUser();if(!user)return login();profile=await getProfile(user.id);if(!profile)return denied();await load();renderPage()}
supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){profile=null;items=[];login()}});
start();
