import { createClient } from '@supabase/supabase-js';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const weekStorageKey='k3paalbos-weekcalendar-v2';let touchDrag=null,overElement=null,calendarTapSelection=null;
function isTouchPointer(e){return e.pointerType==='touch'||e.pointerType==='pen'}
function clearOver(){if(overElement){overElement.classList.remove('over');overElement=null}}
function point(x,y,selector){return document.elementFromPoint(x,y)?.closest(selector)||null}
function pointTarget(e,s){return point(e.clientX,e.clientY,s)}
function readWeek(){try{return {days:{},activities:{},...(JSON.parse(localStorage.getItem(weekStorageKey))||{})}}catch{return {days:{},activities:{}}}}
function saveWeek(s){localStorage.setItem(weekStorageKey,JSON.stringify(s))}
function rerenderWeek(){window.dispatchEvent(new CustomEvent('k3paalbos:navigate',{detail:{page:'week'}}))}
function clearCalendarSelection(){document.querySelectorAll('.icon.tap-selected').forEach(x=>x.classList.remove('tap-selected'));calendarTapSelection=null;document.body.classList.remove('calendar-tap-place')}
function selectCalendarIcon(source,item){clearCalendarSelection();calendarTapSelection=item;source.classList.add('tap-selected');document.body.classList.add('calendar-tap-place')}
async function placeCalendar(item,day){const dayKey=day?.dataset.day;if(!dayKey)return false;const {count,error:ce}=await supabase.from('calendar_items').select('id',{count:'exact',head:true}).eq('day',dayKey);if(ce){alert(`Kon kalender niet lezen: ${ce.message}`);return false}const {error}=await supabase.from('calendar_items').insert({day:dayKey,icon:item.icon,label:item.label,position:count||0});if(error){alert(`Kon activiteit niet opslaan: ${error.message}`);return false}clearCalendarSelection();document.querySelector('.nav-item[data-page="calendar"]')?.click();return true}
function calendarItem(source){return {kind:'calendar',icon:source.querySelector('span')?.textContent||'',label:source.querySelector('small')?.textContent||''}}
function startTouchDrag(e){if(!isTouchPointer(e)||e.button!==0)return;const source=e.target.closest('.icon,.day-token,.placed-day,.activity-token,.week-activity');if(!source||e.target.closest('.remove-week,.remove'))return;if(source.matches('.icon')){touchDrag={...calendarItem(source),startX:e.clientX,startY:e.clientY,moved:false};selectCalendarIcon(source,touchDrag)}else if(source.matches('.day-token,.placed-day')){const id=Number(source.dataset.dayId);if(!id)return;const names=['','Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'],colors=['','green','green','wednesday','green','green','blue','blue'];touchDrag={kind:'week-day',day:{id,name:names[id],color:colors[id]}}}else if(source.matches('.activity-token'))touchDrag={kind:'week-activity',activity:{icon:source.querySelector('span')?.textContent||'',label:source.querySelector('small')?.textContent||''}};else if(source.matches('.week-activity')){const state=readWeek(),from=Number(source.dataset.actDay),index=Number(source.dataset.actIndex),activity=(state.activities[from]||[])[index];if(!activity)return;touchDrag={kind:'week-move-activity',activity:{...activity},from,index}}if(!touchDrag)return;e.preventDefault();e.stopImmediatePropagation();source.classList.add('touch-dragging');touchDrag.source=source;touchDrag.pointerId=e.pointerId}
function moveTouchDrag(e){if(!touchDrag||e.pointerId!==touchDrag.pointerId)return;if(touchDrag.kind==='calendar'&&Math.hypot(e.clientX-touchDrag.startX,e.clientY-touchDrag.startY)>8)touchDrag.moved=true;e.preventDefault();clearOver();const s=touchDrag.kind==='calendar'?'.day:not(.empty)':touchDrag.kind==='week-day'?'.week-column':'.activity-zone',t=pointTarget(e,s);if(t){t.classList.add('over');overElement=t}}
async function finishTouchDrag(e){if(!touchDrag||e.pointerId!==touchDrag.pointerId)return;e.preventDefault();e.stopImmediatePropagation();const d=touchDrag;touchDrag=null;clearOver();d.source?.classList.remove('touch-dragging');if(d.kind==='calendar'){if(d.moved){const day=pointTarget(e,'.day:not(.empty)');if(day)await placeCalendar(d,day)}return}if(d.kind==='week-day'){const c=pointTarget(e,'.week-column');if(!c)return;const slot=Number(c.dataset.slot),s=readWeek();Object.keys(s.days).forEach(k=>{if(s.days[k]?.id===d.day.id)delete s.days[k]});s.days[slot]=d.day;saveWeek(s);rerenderWeek();return}const z=pointTarget(e,'.activity-zone');if(!z)return;const day=Number(z.dataset.activityDay),s=readWeek(),max=day===3?4:5;if(d.kind==='week-activity'){if((s.activities[day]||[]).length>=max)return;(s.activities[day]||(s.activities[day]=[])).push(d.activity)}else{if(day!==d.from&&(s.activities[day]||[]).length>=max)return;s.activities[d.from]=(s.activities[d.from]||[]).filter((_,i)=>i!==d.index);(s.activities[day]||(s.activities[day]=[])).push(d.activity)}saveWeek(s);rerenderWeek()}
function cancelTouchDrag(e){if(!touchDrag||e.pointerId!==touchDrag.pointerId)return;touchDrag.source?.classList.remove('touch-dragging');touchDrag=null;clearOver()}
// iPad Safari can suppress the synthetic click after a prevented pointer event.
// Handle tap-to-place on pointerup itself, using the exact same event path as the working week calendar.
async function calendarDayPointerUp(e){if(!isTouchPointer(e)||!calendarTapSelection||touchDrag)return;const day=e.target.closest?.('.day:not(.empty)')||pointTarget(e,'.day:not(.empty)');if(!day)return;e.preventDefault();e.stopImmediatePropagation();await placeCalendar(calendarTapSelection,day)}
async function calendarDayTouchEnd(e){if(!calendarTapSelection||touchDrag)return;const t=e.changedTouches?.[0];if(!t)return;const day=point(t.clientX,t.clientY,'.day:not(.empty)');if(!day)return;e.preventDefault();e.stopImmediatePropagation();await placeCalendar(calendarTapSelection,day)}
async function calendarMouseClick(e){if(!calendarTapSelection)return;const day=e.target.closest?.('.day:not(.empty)');if(!day)return;e.preventDefault();e.stopImmediatePropagation();await placeCalendar(calendarTapSelection,day)}
document.addEventListener('pointerdown',startTouchDrag,{capture:true,passive:false});document.addEventListener('pointermove',moveTouchDrag,{capture:true,passive:false});document.addEventListener('pointerup',finishTouchDrag,{capture:true,passive:false});document.addEventListener('pointerup',calendarDayPointerUp,{capture:true,passive:false});document.addEventListener('pointercancel',cancelTouchDrag,true);document.addEventListener('touchend',calendarDayTouchEnd,{capture:true,passive:false});document.addEventListener('click',calendarMouseClick,true);
