const originalFetch=globalThis.fetch.bind(globalThis);
let weekStateCache=null,userCache=null,weekSaveQueue=Promise.resolve();
function isWeekStateUrl(input){const url=typeof input==='string'?input:input?.url||'';return url.includes('/rest/v1/week_calendar_state')}
function isUserUrl(input){const url=typeof input==='string'?input:input?.url||'';return url.includes('/auth/v1/user')}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json'}})}
globalThis.fetch=async function(input,init){const method=(init?.method||(typeof input!=='string'&&input?.method)||'GET').toUpperCase();if(isUserUrl(input)&&method==='GET'&&userCache)return jsonResponse(userCache);if(!isWeekStateUrl(input)){const response=await originalFetch(input,init);if(isUserUrl(input)&&method==='GET'&&response.ok){try{userCache=await response.clone().json()}catch{}}return response}if(method==='GET'&&weekStateCache!==null){const accept=(init?.headers&&new Headers(init.headers).get('accept'))||'';return jsonResponse(accept.includes('vnd.pgrst.object')?{state:weekStateCache}:[{state:weekStateCache}])}if(method==='GET'){const response=await originalFetch(input,init);if(response.ok){try{const data=await response.clone().json();if(Array.isArray(data)&&data[0]?.state)weekStateCache=data[0].state;else if(data?.state)weekStateCache=data.state}catch{}}return response}if(method==='PATCH'||method==='POST'){let body=null;try{body=typeof init?.body==='string'?JSON.parse(init.body):null}catch{}if(body?.state!==undefined)weekStateCache=body.state;weekSaveQueue=weekSaveQueue.then(async()=>{try{const response=await originalFetch(input,init);if(!response.ok)console.error('Weekkalender opslaan mislukt:',response.status,response.statusText)}catch(error){console.error('Weekkalender opslaan mislukt:',error)}});return new Response('',{status:204})}return originalFetch(input,init)};

import { createClient } from '@supabase/supabase-js';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
let calendarTapSelection=null,calendarPlacementBusy=false;
function isTouchPointer(e){return e.pointerType==='touch'||e.pointerType==='pen'}
function point(x,y,selector){return document.elementFromPoint(x,y)?.closest(selector)||null}
function calendarDayAt(x,y){const exact=point(x,y,'.day:not(.empty)');if(exact)return exact;let best=null,bestDistance=Infinity;document.querySelectorAll('.calendar .day:not(.empty)').forEach(day=>{const r=day.getBoundingClientRect(),pad=14;if(x<r.left-pad||x>r.right+pad||y<r.top-pad||y>r.bottom+pad)return;const dx=x<r.left?r.left-x:x>r.right?x-r.right:0,dy=y<r.top?r.top-y:y>r.bottom?y-r.bottom:0,d=Math.hypot(dx,dy);if(d<bestDistance){best=day;bestDistance=d}});return best}
function clearCalendarSelection(){document.querySelectorAll('.calendar-activity-token.tap-selected,.icon.tap-selected').forEach(x=>x.classList.remove('tap-selected'));calendarTapSelection=null;document.body.classList.remove('calendar-tap-place')}
function selectCalendarIcon(source,item){clearCalendarSelection();calendarTapSelection=item;source.classList.add('tap-selected');document.body.classList.add('calendar-tap-place')}
function showPlacedCalendarItem(day,item){const items=day?.querySelector('.day-items');if(!items)return;const placed=document.createElement('div');placed.className='placed';placed.innerHTML=`<span>${item.icon}</span><small>${item.label}</small>${item.id?`<button class="remove" data-id="${item.id}">×</button>`:''}`;const remove=placed.querySelector('.remove');if(remove)remove.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();const {error}=await supabase.from('calendar_items').delete().eq('id',item.id);if(!error)placed.remove()});items.appendChild(placed)}
async function placeCalendar(item,day){const dayKey=day?.dataset.day;if(!dayKey||calendarPlacementBusy)return false;calendarPlacementBusy=true;try{const {count,error:ce}=await supabase.from('calendar_items').select('id',{count:'exact',head:true}).eq('day',dayKey);if(ce){alert(`Kon kalender niet lezen: ${ce.message}`);return false}const {data,error}=await supabase.from('calendar_items').insert({day:dayKey,icon:item.icon,label:item.label,position:count||0}).select('id,day,icon,label,position').single();if(error){alert(`Kon activiteit niet opslaan: ${error.message}`);return false}showPlacedCalendarItem(day,data||{...item,day:dayKey});clearCalendarSelection();return true}finally{calendarPlacementBusy=false}}
function calendarItem(source){return {kind:'calendar',icon:source.querySelector('span')?.textContent||'',label:source.querySelector('small')?.textContent||''}}
function startTouchDrag(e){if(!isTouchPointer(e)||e.button!==0)return;const source=e.target.closest('.calendar-activity-token,.icon');if(!source||e.target.closest('.remove'))return;selectCalendarIcon(source,calendarItem(source))}
async function calendarDayPointerUp(e){if(!isTouchPointer(e)||!calendarTapSelection)return;const day=calendarDayAt(e.clientX,e.clientY);if(!day)return;e.preventDefault();e.stopImmediatePropagation();await placeCalendar(calendarTapSelection,day)}
async function calendarMouseClick(e){if(!calendarTapSelection)return;const day=e.target.closest?.('.day:not(.empty)');if(!day)return;e.preventDefault();e.stopImmediatePropagation();await placeCalendar(calendarTapSelection,day)}
document.addEventListener('pointerdown',startTouchDrag,{capture:true,passive:false});document.addEventListener('pointerup',calendarDayPointerUp,{capture:true,passive:false});document.addEventListener('click',calendarMouseClick,true);
